/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvRouteImport } from './routes/cv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as SchedulerIndexRouteImport } from './routes/scheduler/index'
import { Route as SchedulerPlanRouteImport } from './routes/scheduler/plan'
import { Route as SchedulerTransferredRouteImport } from './routes/scheduler/transferred'
import { Route as TrackerIndexRouteImport } from './routes/tracker/index'
import { Route as TrackerProjectRouteImport } from './routes/tracker/$project'
import { Route as TrackerAttendanceRouteImport } from './routes/tracker/attendance'
import { Route as TrackerProjectIndexRouteImport } from './routes/tracker/$project/index'
import { Route as TrackerProjectConceptsRouteImport } from './routes/tracker/$project/concepts'
import { Route as TrackerProjectGuideRouteImport } from './routes/tracker/$project/guide'
import { Route as TrackerProjectProgressRouteImport } from './routes/tracker/$project/progress'
import { Route as TrackerProjectReflectRouteImport } from './routes/tracker/$project/reflect'
import { Route as TrackerProjectTasksTaskIdRouteImport } from './routes/tracker/$project/tasks/$taskId'
import { Route as TrackerProjectTasksTaskIdSessionRouteImport } from './routes/tracker/$project/tasks/$taskId_.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerIndexRoute = SchedulerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchedulerRoute,
} as any)
const SchedulerPlanRoute = SchedulerPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => SchedulerRoute,
} as any)
const SchedulerTransferredRoute = SchedulerTransferredRouteImport.update({
  id: '/transferred',
  path: '/transferred',
  getParentRoute: () => SchedulerRoute,
} as any)
const TrackerIndexRoute = TrackerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackerRoute,
} as any)
const TrackerProjectRoute = TrackerProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => TrackerRoute,
} as any)
const TrackerAttendanceRoute = TrackerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TrackerRoute,
} as any)
const TrackerProjectIndexRoute = TrackerProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackerProjectRoute,
} as any)
const TrackerProjectConceptsRoute = TrackerProjectConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => TrackerProjectRoute,
} as any)
const TrackerProjectGuideRoute = TrackerProjectGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => TrackerProjectRoute,
} as any)
const TrackerProjectProgressRoute = TrackerProjectProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TrackerProjectRoute,
} as any)
const TrackerProjectReflectRoute = TrackerProjectReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => TrackerProjectRoute,
} as any)
const TrackerProjectTasksTaskIdRoute =
  TrackerProjectTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => TrackerProjectRoute,
  } as any)
const TrackerProjectTasksTaskIdSessionRoute =
  TrackerProjectTasksTaskIdSessionRouteImport.update({
    id: '/tasks/$taskId_/session',
    path: '/tasks/$taskId/session',
    getParentRoute: () => TrackerProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRouteWithChildren
  '/tracker': typeof TrackerRouteWithChildren
  '/scheduler/plan': typeof SchedulerPlanRoute
  '/scheduler/transferred': typeof SchedulerTransferredRoute
  '/tracker/$project': typeof TrackerProjectRouteWithChildren
  '/tracker/attendance': typeof TrackerAttendanceRoute
  '/scheduler/': typeof SchedulerIndexRoute
  '/tracker/': typeof TrackerIndexRoute
  '/tracker/$project/concepts': typeof TrackerProjectConceptsRoute
  '/tracker/$project/guide': typeof TrackerProjectGuideRoute
  '/tracker/$project/progress': typeof TrackerProjectProgressRoute
  '/tracker/$project/reflect': typeof TrackerProjectReflectRoute
  '/tracker/$project/': typeof TrackerProjectIndexRoute
  '/tracker/$project/tasks/$taskId': typeof TrackerProjectTasksTaskIdRoute
  '/tracker/$project/tasks/$taskId/session': typeof TrackerProjectTasksTaskIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/login': typeof LoginRoute
  '/scheduler/plan': typeof SchedulerPlanRoute
  '/scheduler/transferred': typeof SchedulerTransferredRoute
  '/tracker/attendance': typeof TrackerAttendanceRoute
  '/scheduler': typeof SchedulerIndexRoute
  '/tracker': typeof TrackerIndexRoute
  '/tracker/$project/concepts': typeof TrackerProjectConceptsRoute
  '/tracker/$project/guide': typeof TrackerProjectGuideRoute
  '/tracker/$project/progress': typeof TrackerProjectProgressRoute
  '/tracker/$project/reflect': typeof TrackerProjectReflectRoute
  '/tracker/$project': typeof TrackerProjectIndexRoute
  '/tracker/$project/tasks/$taskId': typeof TrackerProjectTasksTaskIdRoute
  '/tracker/$project/tasks/$taskId/session': typeof TrackerProjectTasksTaskIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/login': typeof LoginRoute
  '/scheduler': typeof SchedulerRouteWithChildren
  '/tracker': typeof TrackerRouteWithChildren
  '/scheduler/plan': typeof SchedulerPlanRoute
  '/scheduler/transferred': typeof SchedulerTransferredRoute
  '/tracker/$project': typeof TrackerProjectRouteWithChildren
  '/tracker/attendance': typeof TrackerAttendanceRoute
  '/scheduler/': typeof SchedulerIndexRoute
  '/tracker/': typeof TrackerIndexRoute
  '/tracker/$project/concepts': typeof TrackerProjectConceptsRoute
  '/tracker/$project/guide': typeof TrackerProjectGuideRoute
  '/tracker/$project/progress': typeof TrackerProjectProgressRoute
  '/tracker/$project/reflect': typeof TrackerProjectReflectRoute
  '/tracker/$project/': typeof TrackerProjectIndexRoute
  '/tracker/$project/tasks/$taskId': typeof TrackerProjectTasksTaskIdRoute
  '/tracker/$project/tasks/$taskId_/session': typeof TrackerProjectTasksTaskIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/login'
    | '/scheduler'
    | '/tracker'
    | '/scheduler/plan'
    | '/scheduler/transferred'
    | '/tracker/$project'
    | '/tracker/attendance'
    | '/scheduler/'
    | '/tracker/'
    | '/tracker/$project/concepts'
    | '/tracker/$project/guide'
    | '/tracker/$project/progress'
    | '/tracker/$project/reflect'
    | '/tracker/$project/'
    | '/tracker/$project/tasks/$taskId'
    | '/tracker/$project/tasks/$taskId/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/login'
    | '/scheduler/plan'
    | '/scheduler/transferred'
    | '/tracker/attendance'
    | '/scheduler'
    | '/tracker'
    | '/tracker/$project/concepts'
    | '/tracker/$project/guide'
    | '/tracker/$project/progress'
    | '/tracker/$project/reflect'
    | '/tracker/$project'
    | '/tracker/$project/tasks/$taskId'
    | '/tracker/$project/tasks/$taskId/session'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/login'
    | '/scheduler'
    | '/tracker'
    | '/scheduler/plan'
    | '/scheduler/transferred'
    | '/tracker/$project'
    | '/tracker/attendance'
    | '/scheduler/'
    | '/tracker/'
    | '/tracker/$project/concepts'
    | '/tracker/$project/guide'
    | '/tracker/$project/progress'
    | '/tracker/$project/reflect'
    | '/tracker/$project/'
    | '/tracker/$project/tasks/$taskId'
    | '/tracker/$project/tasks/$taskId_/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  LoginRoute: typeof LoginRoute
  SchedulerRoute: typeof SchedulerRouteWithChildren
  TrackerRoute: typeof TrackerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler/': {
      id: '/scheduler/'
      path: '/'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof SchedulerIndexRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/scheduler/plan': {
      id: '/scheduler/plan'
      path: '/plan'
      fullPath: '/scheduler/plan'
      preLoaderRoute: typeof SchedulerPlanRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/scheduler/transferred': {
      id: '/scheduler/transferred'
      path: '/transferred'
      fullPath: '/scheduler/transferred'
      preLoaderRoute: typeof SchedulerTransferredRouteImport
      parentRoute: typeof SchedulerRoute
    }
    '/tracker/': {
      id: '/tracker/'
      path: '/'
      fullPath: '/tracker/'
      preLoaderRoute: typeof TrackerIndexRouteImport
      parentRoute: typeof TrackerRoute
    }
    '/tracker/$project': {
      id: '/tracker/$project'
      path: '/$project'
      fullPath: '/tracker/$project'
      preLoaderRoute: typeof TrackerProjectRouteImport
      parentRoute: typeof TrackerRoute
    }
    '/tracker/attendance': {
      id: '/tracker/attendance'
      path: '/attendance'
      fullPath: '/tracker/attendance'
      preLoaderRoute: typeof TrackerAttendanceRouteImport
      parentRoute: typeof TrackerRoute
    }
    '/tracker/$project/': {
      id: '/tracker/$project/'
      path: '/'
      fullPath: '/tracker/$project/'
      preLoaderRoute: typeof TrackerProjectIndexRouteImport
      parentRoute: typeof TrackerProjectRoute
    }
    '/tracker/$project/concepts': {
      id: '/tracker/$project/concepts'
      path: '/concepts'
      fullPath: '/tracker/$project/concepts'
      preLoaderRoute: typeof TrackerProjectConceptsRouteImport
      parentRoute: typeof TrackerProjectRoute
    }
    '/tracker/$project/guide': {
      id: '/tracker/$project/guide'
      path: '/guide'
      fullPath: '/tracker/$project/guide'
      preLoaderRoute: typeof TrackerProjectGuideRouteImport
      parentRoute: typeof TrackerProjectRoute
    }
    '/tracker/$project/progress': {
      id: '/tracker/$project/progress'
      path: '/progress'
      fullPath: '/tracker/$project/progress'
      preLoaderRoute: typeof TrackerProjectProgressRouteImport
      parentRoute: typeof TrackerProjectRoute
    }
    '/tracker/$project/reflect': {
      id: '/tracker/$project/reflect'
      path: '/reflect'
      fullPath: '/tracker/$project/reflect'
      preLoaderRoute: typeof TrackerProjectReflectRouteImport
      parentRoute: typeof TrackerProjectRoute
    }
    '/tracker/$project/tasks/$taskId': {
      id: '/tracker/$project/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tracker/$project/tasks/$taskId'
      preLoaderRoute: typeof TrackerProjectTasksTaskIdRouteImport
      parentRoute: typeof TrackerProjectRoute
    }
    '/tracker/$project/tasks/$taskId_/session': {
      id: '/tracker/$project/tasks/$taskId_/session'
      path: '/tasks/$taskId/session'
      fullPath: '/tracker/$project/tasks/$taskId/session'
      preLoaderRoute: typeof TrackerProjectTasksTaskIdSessionRouteImport
      parentRoute: typeof TrackerProjectRoute
    }
  }
}

interface SchedulerRouteChildren {
  SchedulerPlanRoute: typeof SchedulerPlanRoute
  SchedulerTransferredRoute: typeof SchedulerTransferredRoute
  SchedulerIndexRoute: typeof SchedulerIndexRoute
}

const SchedulerRouteChildren: SchedulerRouteChildren = {
  SchedulerPlanRoute: SchedulerPlanRoute,
  SchedulerTransferredRoute: SchedulerTransferredRoute,
  SchedulerIndexRoute: SchedulerIndexRoute,
}

const SchedulerRouteWithChildren = SchedulerRoute._addFileChildren(
  SchedulerRouteChildren,
)

interface TrackerProjectRouteChildren {
  TrackerProjectConceptsRoute: typeof TrackerProjectConceptsRoute
  TrackerProjectGuideRoute: typeof TrackerProjectGuideRoute
  TrackerProjectProgressRoute: typeof TrackerProjectProgressRoute
  TrackerProjectReflectRoute: typeof TrackerProjectReflectRoute
  TrackerProjectIndexRoute: typeof TrackerProjectIndexRoute
  TrackerProjectTasksTaskIdRoute: typeof TrackerProjectTasksTaskIdRoute
  TrackerProjectTasksTaskIdSessionRoute: typeof TrackerProjectTasksTaskIdSessionRoute
}

const TrackerProjectRouteChildren: TrackerProjectRouteChildren = {
  TrackerProjectConceptsRoute: TrackerProjectConceptsRoute,
  TrackerProjectGuideRoute: TrackerProjectGuideRoute,
  TrackerProjectProgressRoute: TrackerProjectProgressRoute,
  TrackerProjectReflectRoute: TrackerProjectReflectRoute,
  TrackerProjectIndexRoute: TrackerProjectIndexRoute,
  TrackerProjectTasksTaskIdRoute: TrackerProjectTasksTaskIdRoute,
  TrackerProjectTasksTaskIdSessionRoute: TrackerProjectTasksTaskIdSessionRoute,
}

const TrackerProjectRouteWithChildren = TrackerProjectRoute._addFileChildren(
  TrackerProjectRouteChildren,
)

interface TrackerRouteChildren {
  TrackerProjectRoute: typeof TrackerProjectRouteWithChildren
  TrackerAttendanceRoute: typeof TrackerAttendanceRoute
  TrackerIndexRoute: typeof TrackerIndexRoute
}

const TrackerRouteChildren: TrackerRouteChildren = {
  TrackerProjectRoute: TrackerProjectRouteWithChildren,
  TrackerAttendanceRoute: TrackerAttendanceRoute,
  TrackerIndexRoute: TrackerIndexRoute,
}

const TrackerRouteWithChildren =
  TrackerRoute._addFileChildren(TrackerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  LoginRoute: LoginRoute,
  SchedulerRoute: SchedulerRouteWithChildren,
  TrackerRoute: TrackerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
